dhall-to-cabal.cabal
dhall-to-cabal.dhall
dhall/types/Guarded.dhall
dhall/unconditional.dhall
exe/Main.hs
golden-tests/conditions.dhall
lib/DhallToCabal/ConfigTree.hs
lib/DhallToCabal/Diff.hs
lib/Distribution/Package/Dhall.hs

This commit changes the guarding logic from:
List { guard : Config -> Bool, body : A }
to simply
Config -> A
This is achieved through the new ConfigTree type.
ConfigTree takes the unsaturated configuration lambda, and applies it with a
known variable name. Next, we find all uses of this variable w.r.t. config field
access and application. We then replace all occurances of these applications
with either True or False, building a tree of decisions as we go - this is the
ConfigTree.
With a ConfigTree extracted, it's trivial to then turn this into a
Cabal.CondTree.
This currently produces some verbose Cabal, but it's not going to be much work
to lift common elements up the tree and produce miminal Cabal files. This will
come in future work.

Change guarding to be a top level function per component

---

dhall/types.dhall

This exports everything from dhall/types/*.dhall that's not obviously
internal, for user convenience.
Also more random trailing whitespace got removed in the process.

Export more types through dhall/types.dhall.

---

dhall/types.dhall

Managed to miss this rather important one in #40. Oops.

Also export Package from types.dhall.

---

dhall/types.dhall

Annoyingly, Guarded is higher-kinded and in Dhall 1.13 cannot be part
of a record.

Un-export Guarded from types.dhall

---

cabal-to-dhall/Main.hs
dhall/types.dhall

This is consistent with the filename, and how it's used in the
examples.
Note that this is a breaking API change.

Rename types.ConfigOptions to types.Config.

---

dhall/defaults/Package.dhall

Along with version, this is one of the fields that it just doesn't
make sense to do without.

Don't provide a default name for packages.

---

dhall-to-cabal.cabal
dhall-to-cabal.dhall
dhall.nix
lib/CabalToDhall.hs

Extends @quasicomputational's pull request and also regenerates `dhall.nix` for Hydra.

Upgrade to Dhall 1.14.

---

Changelog.md
cabal-to-dhall/Main.hs
dhall-to-cabal.cabal
dhall-to-cabal.dhall
golden-tests/GoldenTests.hs
golden-tests/cabal-to-dhall/conditional-dependencies.dhall
golden-tests/cabal-to-dhall/gh-36.dhall
golden-tests/cabal-to-dhall/simple.dhall
lib/CabalToDhall.hs

This will grab the current version number from Paths_dhall_to_cabal
and then generate the URL to import from from that.
As a knock-on change, to prevent the tests breaking every time the
version is bumped, we now omit the imports altogether from
cabal-to-dhall's tests.

cabal-to-dhall: keep the generated imports from GitHub up to date

---

Changelog.md
dhall/defaults/Executable.dhall
golden-tests/dhall-to-cabal/empty-package.cabal
golden-tests/dhall-to-cabal/empty-package.dhall

Much like #46, this is a field that it is not sensible to do without.

Omit main-is from the default Executable.

---

Changelog.md
cabal-to-dhall/Main.hs
dhall-to-cabal.cabal
dhall-to-cabal.dhall
exe/Main.hs
golden-tests/GoldenTests.hs
lib/CabalToDhall.hs
lib/DhallLocation.hs

`Extension` is fairly large and it's not particularly illuminating to
scroll through, so refer to it by an import unless it's the specific
type that the user has asked for.
A new option, `--self-contained`, disables the reference-by-import
and, as the name suggests, makes `--print-type` output fully
self-contained.
Closes #69.
Not quite in a mergeable state yet; best to wait for #66 and then refactor the `typesLocation` boilerplate into a central location, and in the meantime the code wants a little tidying.

WIP: print-type: Refer to the Extension union by import.

---

dhall-to-cabal.cabal
dhall-to-cabal.dhall

Hackage complains:
> Packages using 'cabal-version: 2.0' and the autogenerated module Paths_* must
> include it also on the 'autogen-modules' field besides 'exposed-modules' and
> 'other-modules'. This specifies that the module does not come with the package
> and is generated on setup. Modules built with a custom Setup.hs script also go
> here to ensure that commands like sdist don't fail.

Also add Paths_dhall_to_cabal to autogen-modules

---

dhall/defaults/Library.dhall

defaults/BuildInfo.dhall already includes an other-modules field.

Don't double up on other-modules in defaults/Library.dhall

---

golden-tests/cabal-to-dhall/SPDX.dhall
golden-tests/cabal-to-dhall/conditional-dependencies.dhall
golden-tests/cabal-to-dhall/gh-36.dhall
golden-tests/cabal-to-dhall/otheros.dhall
golden-tests/cabal-to-dhall/simple.dhall
lib/CabalToDhall.hs

This removes a use of runUnion (#84) and produces much friendlier
output.
Originally part of #83, but this is a separable change that we want
anyway, no matter which direction that PR goes.

Refactor license in CabalToDhall

---

Changelog.md
cabal-to-dhall/Main.hs
golden-tests/GoldenTests.hs
lib/CabalToDhall.hs

Also expose parseGenericPackageDescriptionThrows, a new convenience
function.
This is useful because any external consumers of the CabalToDhall API
will likely have a GenericPackageDescription on hand; rather than
serialising it only to pass it in and have it re-parsed, skipping the
indirection makes sense.

CabalToDhall: make cabalToDhall a pure function.

---

Changelog.md
dhall/defaults/Package.dhall
golden-tests/cabal-to-dhall/default-license-2.2.cabal
golden-tests/cabal-to-dhall/default-license-2.2.dhall
golden-tests/dhall-to-cabal/allrightsreserved-2.0.cabal
golden-tests/dhall-to-cabal/allrightsreserved-2.0.dhall
golden-tests/dhall-to-cabal/allrightsreserved-2.2.cabal
golden-tests/dhall-to-cabal/allrightsreserved-2.2.dhall
golden-tests/dhall-to-cabal/compiler-options-order.cabal
golden-tests/dhall-to-cabal/conditional-dependencies.cabal
golden-tests/dhall-to-cabal/default-license-2.2.cabal
golden-tests/dhall-to-cabal/default-license-2.2.dhall
golden-tests/dhall-to-cabal/gh-53.cabal
golden-tests/dhall-to-cabal/gh-55.cabal
golden-tests/dhall-to-cabal/map-source-repo.cabal
golden-tests/dhall-to-cabal/nested-conditions.cabal
lib/CabalToDhall.hs
lib/DhallToCabal.hs

Cabal always reports a `.cabal` file missing the `license` field as
having a license of SPDX.NONE, even for `cabal-version: 2.0`.

Map between SPDX.NONE and AllRightsReserved depending on cabal-version

---

dhall-to-cabal.cabal
dhall-to-cabal.dhall
stack.yaml

After changes to bump cabal spec version of dhall-to-cabal to 2.2 the project cant be built with stack. I've found 2 issues:
* Last lts can't build cabal files with spec > 2.0 -> i've changed the resolver to nightly
* Even with nightly, stack cant build cabal files without build-type (it thinks that is `custom` by default like cabal spec < 2.2 and throws an error: `No Setup.hs or Setup.lhs file found in D:\ws\eta\dhall\dhall-to-etlas\`).
At least with my version: 1.6.5

Changes to allow stack build the project

---

lib/Dhall/Extra.hs
lib/DhallToCabal.hs

I've chosen the easy path of keeping the existing type and functions and making it alias for the dhall ones. Let me know if you think that the best option would be remove them and replace for the new ones.

Refactor Dhall.Extra to use utils for build records of dhall >= 1.13

---

dhall-to-cabal.cabal
dhall-to-cabal.dhall

I guess no-one has been testing the sdists, so this was only uncovered
by Stackage.
Should fix commercialhaskell/stackage#3899.

Add missing dhall/types/BuildInfo.dhall to extra-source-files.

---

Changelog.md
dhall/prelude.dhall
dhall/types/ModuleRenaming.dhall
golden-tests/cabal-to-dhall/mixins-no-signatures.cabal
golden-tests/cabal-to-dhall/mixins-no-signatures.dhall
golden-tests/dhall-to-cabal/mixins-no-signatures.cabal
golden-tests/dhall-to-cabal/mixins-no-signatures.dhall
lib/CabalToDhall.hs
lib/DhallToCabal.hs

Previously, only the `ModuleRenaming` case was handled. However, there
are two other cases: `DefaultRenaming` and `HidingRenaming`. This
commit adds support for both of those, reducing one more place where
`cabal-to-dhall` can crash.
On the Dhall side, types/ModuleRenaming.dhall is now a union that
closely matches its Cabal-side reflection. The constructors of this
union are exported through the prelude for convenience.
There may be some room for additional convenience functions in Dhall
here, but I'm happy with just having the functionality available.

Fully support the mixins field.

---

Changelog.md
dhall-to-cabal.cabal
dhall-to-cabal.dhall
dhall.nix
lib/DhallLocation.hs
stack.yaml

To help unblock commercialhaskell/stackage#3945.
Not sure if this should go in and be released until we figure out what's up with #124. If it's a pre-existing problem I'd say to go for it, but if it's a regression we should hold back, and since we don't know we've got to assume it's a regression.

Allow dhall-1.17.

---

Changelog.md
dhall-to-cabal.cabal
dhall-to-cabal.dhall

There are actually no breaking API changes this release that I can see (https://github.com/dhall-lang/dhall-to-cabal/compare/1.3.0.0...master), so this takes us from 1.3.0.1 to 1.3.1.0.
Fixes #139.

Release 1.3.1.0

---

golden-tests/GoldenTests.hs

Use Diff package instead diff program to test cabal-to-dhall

---

stack.yaml

Should've done this as part of #149 - ah well. I did make sure it
worked on the other two build systems!

Bump nightly resolver to one with Dhall 1.21 in it.

---

.gitattributes
README.md

Sets syntax highlighting for Dhall files using `.gitattributes`, refer to https://github.com/dhall-lang/dhall-lang/pull/533 for details.
This also updates the examples in the readme to use the relevant language for syntax highlighting.

Syntax highlighting

---

Changelog.md
golden-tests/cabal-to-dhall/unknown-license.cabal
golden-tests/cabal-to-dhall/unknown-license.dhall
lib/CabalToDhall.hs

As discused in https://github.com/dhall-lang/dhall-to-cabal/pull/150#discussion_r283276452
Setting an unkown license with cabal spec < 2.0 throwed an error cause `License.Unspecified` doesnt take a `Text` arg

Use License.Unknown instead License.Unspecified

---

Changelog.md
dhall/defaults/Package.dhall
dhall/types.dhall
dhall/types/CustomSetup.dhall
dhall/types/Package.dhall
lib/CabalToDhall.hs

The files are identical, and the decider in favour of doing it this
way around is that SBI was used in slightly more places than CS.
In *theory* it makes sense to separate the buildinfo-ish parts from
the other parts, but in practice the latter set is null, and there's
unlikely to ever be something that'll work similarly enough to
custom-setup that it'll warrant the sharing.
squash! Remove CustomSetup in favour of SetupBuildInfo.

Remove CustomSetup in favour of SetupBuildInfo.

---

Changelog.md
dhall/types.dhall
dhall/types/ForeignLibOption.dhall
dhall/types/ForeignLibType.dhall
dhall/types/ForeignLibrary.dhall
exe/Main.hs
lib/CabalToDhall.hs
lib/DhallToCabal.hs

`runUnion` stops GHC helping us out with case exhaustivity checking.
In the course of making this PR and getting the benefit of GHC's assistance, I discovered that we weren't handling `AArch64` properly, which is an obvious and easily corrected oversight.
It's also made two other incomplete matches visible, but they're slightly less obviously corrected. As this PR isn't making things worse, only revealing problems that already existed, I've elected to leave those as they are.

Replace & remove runUnion

---

.gitattributes

Now that https://github.com/dhall-lang/dhall-lang/issues/198 has been deployed on GItHub, we'll get proper recognition for Dhall files

Switch to native GitHub highlighting for .dhall

---

Changelog.md
dhall-to-cabal.dhall
dhall/types.dhall
dhall/utils/mapBuildInfo.dhall
dhall/utils/package.dhall
golden-tests/dhall-to-cabal/map-build-info.cabal
golden-tests/dhall-to-cabal/map-build-info.dhall

IMO, this is a function that highlights how `dhall-to-cabal` is an advance on `hpack`: the best feature of `hpack`, setting `ghc-options` at the top level and then having them apply to all components without any per-component effort, is now really easy to implement. It was writable before the latest Dhall version, but record projection by expression turns it from horrible to just mildly repetetive.
Tests are actually passing but I don't think its ready to merge on two counts:
* dhall-lang/dhall-haskell#1009 means that, in `mapBuildInfo.dhall`, the `BuildInfo` used as a field selector has to be an import. This hack is localised and could be noted for later removal and then merged, but...
* We'll want to work out what to do about the imports from Dhall's prelude. I don't really like the …

Add prelude.utils.mapBuildInfo.

---

.gitignore
dhall-to-cabal.cabal
dhall-to-cabal.dhall

* It extracts the common dependencies and `default-language`: the benefit is not terrible but i think it shows the potential of the new function added by @quasicomputational

 Use mapBuildInfo to extract more common build-info fields
